# START
# docker-compose up --build

# STOP
# docker-compose down
version: "3.9"
services:
  backend:
    build: .
    ports:
      - 8000:8000
    entrypoint: './main'

  frontend:
    build: frontend
    ports:
      - 8080:8080